[default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
solc_version = "0.8.17"

[profile.default]
optimizer = true
optimizer_runs = 200


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
